"""empty message

Revision ID: 0bb61ec14dd8
Revises: a166804c8520
Create Date: 2021-11-17 21:56:37.498607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb61ec14dd8'
down_revision = 'a166804c8520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_news_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_news_owner_id_users'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
