"""empty message

Revision ID: 319581d11cec
Revises: fcc20f26db17
Create Date: 2021-10-28 14:34:49.678166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319581d11cec'
down_revision = 'fcc20f26db17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('breeds', sa.String(length=64), nullable=False),
    sa.Column('disposition', sa.String(length=64), nullable=False),
    sa.Column('availability', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('data_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
