"""changed news db

Revision ID: 6046999f4385
Revises: 0bb61ec14dd8
Create Date: 2021-11-17 23:29:01.461762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6046999f4385'
down_revision = '0bb61ec14dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_news_title'), ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_news_title'), type_='unique')

    # ### end Alembic commands ###
