"""empty message

Revision ID: 6e52289c9cad
Revises: 20015fce10dc
Create Date: 2021-11-11 17:11:20.030076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e52289c9cad'
down_revision = '20015fce10dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('img', sa.Text(), nullable=False))
    op.add_column('animals', sa.Column('img_name', sa.Text(), nullable=False))
    op.add_column('animals', sa.Column('img_mimetype', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'animals', ['img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animals', type_='unique')
    op.drop_column('animals', 'img_mimetype')
    op.drop_column('animals', 'img_name')
    op.drop_column('animals', 'img')
    # ### end Alembic commands ###
