"""empty message

Revision ID: 9fb2b676a26d
Revises: cd4499d96811
Create Date: 2021-11-17 21:34:18.517774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb2b676a26d'
down_revision = 'cd4499d96811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
