"""empty message

Revision ID: bfc228e5397f
Revises: 6e52289c9cad
Create Date: 2021-11-11 17:19:04.976803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc228e5397f'
down_revision = '6e52289c9cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('breeds', sa.String(length=64), nullable=False),
    sa.Column('good_with_animal', sa.Boolean(), nullable=False),
    sa.Column('good_with_kid', sa.Boolean(), nullable=False),
    sa.Column('leash_required', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=64), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('img_name', sa.Text(), nullable=False),
    sa.Column('img_mimetype', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('data_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
