"""add Association class

Revision ID: d4af25262fdd
Revises: f60e826a3c43
Create Date: 2021-11-16 22:29:28.736339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4af25262fdd'
down_revision = 'f60e826a3c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_animals_owner_id_users'), 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animals_owner_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
